# Generated by Django 4.2.1 on 2023-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxon_search", "0006_ensemblmetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ensemblmetadata",
            name="strain",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
