# Generated by Django 4.2.1 on 2023-07-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon_search', '0010_taxonflat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnsemblTaxonFlat',
        ),
    ]
