# Generated by Django 3.2.19 on 2023-09-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon_search', '0012_ncbitaxonflat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ncbitaxaname',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ncbitaxaname',
            name='taxon_id',
        ),
        migrations.RemoveField(
            model_name='ncbitaxanode',
            name='parent_id',
        ),
        migrations.DeleteModel(
            name='TaxonFlat',
        ),
        migrations.DeleteModel(
            name='NCBITaxaName',
        ),
        migrations.DeleteModel(
            name='NCBITaxaNode',
        ),
    ]
